export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold mb-4">
        Welcome to Your Generated App
      </h1>
      <p className="text-lg text-gray-600">
        This application was generated by the AI App Builder. Start building
        your amazing application!
      </p>
    </main>
  )
}
